{%- if pillar.ceilometer.server is defined %}
[logstreamer_ceilometer]
type = "LogstreamerInput"
log_directory = "/var/log/ceilometer"
file_match = '(?P<Service>.+)\.log\.?(?P<Index>\d*)?(.gz)?'
differentiator = ["'ceilometer','_','Service'"]
priority = ["^Index"]
decoder = "openstack"
oldest_duration = "168h"

[openstack]
type = "SandboxDecoder"
filename = "lua_modules/decoders/openstack.lua"
module_directory = "/usr/share/heka/lua_modules;/usr/share/heka/lua_modules/common"

{% endif %}
